try
    error "This is an error"
catch e
    print "Caught error: {e.json_encode()}"
end

print "after error"
